name: PowerShell Lint

on:
  push:
    paths:
      - 'scripts/**/*.ps1'
      - '.github/workflows/psscriptanalyzer.yml'
  pull_request:
    paths:
      - 'scripts/**/*.ps1'

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: PowerShell/PowerShell@v1
        with:
          pwsh-version: '7.4'

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./scripts -Recurse -Severity Warning,Error -ReportSummary -EnableExit
